# Generated by Django 5.2.1 on 2025-05-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
