# Generated by Django 5.2.1 on 2025-05-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp_app", "0002_task_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
