# Generated by Django 5.2.1 on 2025-05-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp_app", "0003_remove_task_created_at_remove_task_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="alarm_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
