# Generated by Django 5.2.1 on 2025-05-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp_app", "0004_task_alarm_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="alarm_time",
        ),
    ]
